---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/teresa-carmona/configData
          searchPaths:
        native:
          search-locations: https://github.com/teresa-carmona/configData

server:
  port: 8001
